target-version = "py38"

line-length = 79

format.preview = true

lint.preview = true

lint.select = [
"A",
"B",
"C",
"D",
"E",
"F",
"G",
"I",
"Q",
"S",
"W",
"UP",
"ARG",
"ISC",
"PIE",
#"PTH",
"PYI",
"RET",
"RSE",
"RUF",
"TID",
"TRY",
"YTT",
"FURB",
]

lint.ignore = [
"C901",
]

[lint.isort]
combine-as-imports = true

[lint.per-file-ignores]
".cibw/*" = ["D", "S101"]

[lint.pydocstyle]
convention = "pep257"
