target-version = "py37"

lint.select = [
"A",
"B",
"C",
"D",
"E",
"F",
"G",
"I",
"Q",
"S",
"W",
"UP",
"ISC",
"PIE",
#"PTH",
"RET",
"RUF",
"TRY",
"YTT",
]

lint.ignore = [
]

[lint.per-file-ignores]
".cibw/*" = ["D", "S101"]

[lint.pydocstyle]
convention = "pep257"
