---  # yamllint disable-line rule:document-start
name: 'mpi4py-test-basic'
description: 'Run basic mpi4py tests.'
author: 'Lisandro Dalcin'

inputs:
  shell:
    description: "shell"
    required: false
    default: 'bash'
  python:
    description: "python"
    required: false
    default: 'python'
  mpiexec:
    description: "mpiexec"
    required: false
    default: 'mpiexec'

runs:
  using: 'composite'
  steps:

  - name:  Test mpi4py prefix
    run:   ${{ inputs.python }} -m mpi4py --prefix
    shell: ${{ inputs.shell }}

  - name:  Test mpi4py version
    run:   ${{ inputs.python }} -m mpi4py --version
    shell: ${{ inputs.shell }}

  - name:  Test mpi4py MPI standard version
    run:   ${{ inputs.python }} -m mpi4py --mpi-std-version
    shell: ${{ inputs.shell }}

  - name:  Test mpi4py MPI library version
    run:   ${{ inputs.python }} -m mpi4py --mpi-lib-version
    shell: ${{ inputs.shell }}

  - name:  Test mpi4py helloworld
    run:   >-
      ${{ inputs.mpiexec }} -n 2
      ${{ inputs.python }} -m mpi4py.bench helloworld
    shell: ${{ inputs.shell }}

  - name:  Test mpi4py ringtest
    run:   >-
      ${{ inputs.mpiexec }} -n 2
      ${{ inputs.python }} -m mpi4py.bench ringtest
    shell: ${{ inputs.shell }}
