name: cd-sdist

permissions:
  contents: read

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      repository:
        description: 'mpi4py repository'
        default: mpi4py/mpi4py
        required: false
        type: string
      ref:
        description: 'mpi4py ref'
        default: ''
        required: false
        type: string
  workflow_dispatch:
    inputs:
      repository:
        description: 'mpi4py repository'
        default: mpi4py/mpi4py
        required: true
        type: string
      ref:
        description: 'mpi4py ref'
        default: ''
        required: false
        type: string

jobs:

  sdist:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository || 'mpi4py/mpi4py' }}
        ref: ${{ inputs.ref }}

    - name: Set SOURCE_DATE_EPOCH
      run:  |
        SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
        echo SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH >> $GITHUB_ENV
        echo $(git log -1 --pretty=%ci) [timestamp=$SOURCE_DATE_EPOCH]
      shell: bash

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3

    - name: Upgrade pip
      run:  python -m pip install -U pip

    - name: Install build and twine
      run:  python -m pip install -U build twine

    - name: Build source distribution
      run:  python -m build --sdist

    - name: Check source distribution
      run:  python -m twine check dist/*.tar.gz

    - name: Report sha256sum
      run:  |
        # Report sha256sum
        echo '```'            >> $GITHUB_STEP_SUMMARY
        sha256sum -b *.tar.gz >> $GITHUB_STEP_SUMMARY
        echo '```'            >> $GITHUB_STEP_SUMMARY
      shell: bash
      working-directory: dist

    - name: Upload source distribution
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz
