name: ci

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
    - run: pipx run tox

  wheel-Linux:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      os-arch: Linux

  wheel-macOS:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      os-arch: macOS

  wheel-Windows:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      os-arch: Windows
