name: ci

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:

  wheel-Linux:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      os-arch: Linux

  wheel-macOS:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      os-arch: macOS

  wheel-Windows:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      os-arch: Windows
